# Generated by Django 3.0.1 on 2020-03-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faenas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='Facebook',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='Linkedind',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='Twitter',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='Whatsapp',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace'),
        ),
    ]
