# Generated by Django 3.0.1 on 2020-03-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faenas', '0002_auto_20200327_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='Facebook',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='Linkedind',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='Twitter',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='Whatsapp',
        ),
    ]
